services:
  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio-server
    network_mode: host
    environment:
      IPADDRESS: "192.168.1.100"
      NO_CORS: "1"
    volumes:
      - stremio-data:/root/.stremio-server
    restart: unless-stopped

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: zurg
    network_mode: host
    volumes:
      - ./zurg-config.yml:/app/config.yml
      - zurg-data:/app/data
    restart: unless-stopped

volumes:
  stremio-data:
  zurg-data:
