---

- name: Import macOS tasks
  ansible.builtin.include_tasks: osx.yml
  tags: [osx]

- name: Import homebrew tasks
  ansible.builtin.include_tasks: homebrew.yml
  tags: [osx]

- name: Import upgrade tasks
  ansible.builtin.include_tasks: upgrade.yml
  tags: [upgrade]
